spring:
  application:
    name: reparo

  datasource:
    url: "${DB_URL:jdbc:postgresql://localhost:15432/reparo}"
    username: "${DB_USERNAME:reparo}"
    password: "${DB_PASSWORD:reparo_local_password}"

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate

server:
  address: 127.0.0.1
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health

  endpoint:
    health:
      show-details: always